[package]
name = "nifioxide"
version = "0.1.0"
edition = "2024"
description = "Write HTTP processors for NiFi in Rust."
license = "MIT"
repository = "https://github.com/bsamseth/nifioxide"

[dependencies]
axum = "0.8.8"
futures = "0.3.32"
tempfile = { version = "3.27.0", optional = true }
thiserror = "2.0.18"
tokio = { version = "1.49.0", features = ["full"] }
tokio-util = { version = "0.7.18", features = ["io"] }
tracing = "0.1.44"

[features]
default = ["tempfile"]
tempfile = ["dep:tempfile"]

[dev-dependencies]
anyhow = "1.0.102"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
